// Angular Exporter
// Genera componentes standalone de Angular

import { Injectable } from '@angular/core';
import { ComponentMetadata } from '../models/export.models';
import { ExporterBase } from './exporter-base';

@Injectable({ providedIn: 'root' })
export class AngularExporter extends ExporterBase {
  
  generate(component: ComponentMetadata): string {
    const imports = this.generateImports(component);
    const componentClass = this.generateComponentClass(component);
    const template = this.generateTemplate(component);
    const styles = this.generateStyles(component);

    return `
// Auto-generated by Anto Studios Component Export
// Framework: Angular (Standalone Component)
// Generated: ${new Date().toISOString()}

${imports}

@Component({
  selector: '${this.toKebabCase(component.name)}',
  standalone: true,
  imports: [CommonModule],
  template: \`
${this.indent(template, 4)}
  \`,
  styles: [\`
${this.indent(styles, 4)}
  \`]
})
export class ${component.name}Component {
${this.indent(componentClass, 2)}
}
    `.trim();
  }

  private generateImports(component: ComponentMetadata): string {
    const imports: string[] = ['Component', 'Input', 'Output', 'EventEmitter'];
    
    if (component.props.some(p => p.type === 'function')) {
      imports.push('OnInit', 'OnDestroy');
    }

    return `import { ${imports.join(', ')} } from '@angular/core';
import { CommonModule } from '@angular/common';`;
  }

  private generateComponentClass(component: ComponentMetadata): string {
    // Generate Inputs
    const inputs = component.props.map(p => {
      const type = this.mapTypeToAngular(p.type);
      const defaultVal = p.defaultValue !== undefined 
        ? ` = ${this.formatPropValue(p.defaultValue)}` 
        : '';
      return `@Input() ${p.name}: ${type}${defaultVal};`;
    }).join('\n\n  ');

    // Generate Outputs
    const outputs = component.events.map(e => {
      return `@Output() ${e.name} = new EventEmitter<${this.mapTypeToAngular(e.type)}>();`;
    }).join('\n\n  ');

    // Generate methods
    const methods = `
  constructor() {}

  ngOnInit(): void {
    // Initialize component
  }

  handleClick(event: Event): void {
    this.click.emit(event);
  }
`.trim();

    return `
// Inputs
${inputs}

// Outputs
${outputs}

// Methods
${methods}
    `.trim();
  }

  private generateTemplate(component: ComponentMetadata): string {
    const classBinding = `[class]="'${component.baseClassName}'"`;
    
    const clickHandler = component.events.some(e => e.name === 'click' || e.name === 'onClick')
      ? `(click)="handleClick($event)"`
      : '';

    const disabledBinding = component.props.some(p => p.name === 'disabled')
      ? `[disabled]="disabled"`
      : '';

    return `
<${component.htmlTag}
  ${classBinding}
  ${disabledBinding}
  ${clickHandler}
>
  <ng-content></ng-content>
</${component.htmlTag}>
    `.trim();
  }

  private generateStyles(component: ComponentMetadata): string {
    if (!component.styles || !component.styles.content) {
      return `.${component.baseClassName} {
  /* Add your styles here */
}`;
    }
    return component.styles.content;
  }

  private mapTypeToAngular(type: string): string {
    const typeMap: Record<string, string> = {
      'string': 'string',
      'number': 'number',
      'boolean': 'boolean',
      'function': 'EventEmitter<void>',
      'Event': 'Event'
    };
    return typeMap[type] || 'any';
  }
}
