// React Exporter
// Genera componentes funcionales de React con TypeScript

import { Injectable } from '@angular/core';
import { ComponentMetadata } from '../models/export.models';
import { ExporterBase } from './exporter-base';

@Injectable({ providedIn: 'root' })
export class ReactExporter extends ExporterBase {
  
  generate(component: ComponentMetadata): string {
    const imports = this.generateImports(component);
    const interfaces = this.generateInterfaces(component);
    const componentBody = this.generateComponent(component);
    const styles = this.generateStyles(component);

    return `
// Auto-generated by Anto Studios Component Export
// Framework: React (Functional Component with Hooks)
// Generated: ${new Date().toISOString()}

${imports}

${interfaces}

${componentBody}

${styles}
    `.trim();
  }

  private generateImports(component: ComponentMetadata): string {
    const imports = ['import React'];

    // Detectar uso de hooks
    if (component.props.some(p => p.type === 'function')) {
      imports.push('useCallback', 'useMemo');
    }

    // Imports de props si hay props
    if (component.props.length > 0) {
      imports.push(`import { ${component.name}Props } from './${component.name}.types';`);
    }

    if (imports.length === 1) {
      return "import React from 'react';";
    }

    return `import { ${imports.slice(1).join(', ')} } from 'react';`;
  }

  private generateInterfaces(component: ComponentMetadata): string {
    return this.generatePropsInterface(component.props, component.name);
  }

  private generateComponent(component: ComponentMetadata): string {
    const propsDestructuring = component.props.map(p => {
      const defaultVal = p.defaultValue !== undefined 
        ? ` = ${this.formatPropValue(p.defaultValue)}` 
        : '';
      return `${p.name}${p.required ? '' : '?'}${defaultVal}`;
    }).join(',\n    ');

    const propsType = component.props.length > 0 
      ? `: React.FC<${component.name}Props>` 
      : '';

    const classNameBinding = `const className = \`${component.baseClassName}\${variant ? ' ' + variant : ''}\`.trim();`;
    
    const hasClickHandler = component.events.some(e => e.name === 'click' || e.name === 'onClick');
    const hasDisabled = component.props.some(p => p.name === 'disabled');

    const propsSignature = component.props.length > 0 
      ? `{ ${component.props.map(p => p.name).join(', ')} }: ${component.name}Props`
      : '';

    return `
export const ${component.name}${propsType} = (${propsSignature}) => {
${this.indent(classNameBinding, 2)}

  return (
    <${component.htmlTag}
      className={className}
      ${hasClickHandler ? 'onClick={onClick}' : ''}
      ${hasDisabled ? 'disabled={disabled}' : ''}
      ${this.generateAriaAttributes(component)}
    >
      ${this.generateChildrenContent(component)}
    </${component.htmlTag}>
  );
};
    `.trim();
  }

  private generateChildrenContent(component: ComponentMetadata): string {
    if (component.slots.length > 0) {
      return component.slots.map(s => `<${this.toKebabCase(s.name)} />`).join('\n      ');
    }
    return '{children}';
  }

  private generateAriaAttributes(component: ComponentMetadata): string {
    const ariaProps = component.props
      .filter(p => p.name.startsWith('aria-'))
      .map(p => `${p.name}={${p.name}}`);
    
    return ariaProps.length > 0 
      ? '\n      ' + ariaProps.join('\n      ')
      : '';
  }

  private generateStyles(component: ComponentMetadata): string {
    if (!component.styles || !component.styles.content) return '';

    const styleContent = component.styles.content;

    return `
// Styles (CSS Modules format)
import styles from './${component.name}.module.css';

// OR inline styles:
// const ${component.name}Styles = {
${styleContent.split('}').filter(s => s.trim()).map(rule => {
  const [selector, props] = rule.split('{');
  if (!selector || !props) return '';
  return `//   ${selector}: { ${props.trim()} }`;
}).join('\n')}
// };
    `.trim();
  }
}
