// Web Component Exporter
// Genera Web Components nativos (Vanilla JS)

import { Injectable } from '@angular/core';
import { ComponentMetadata } from '../models/export.models';
import { ExporterBase } from './exporter-base';

@Injectable({ providedIn: 'root' })
export class WebComponentExporter extends ExporterBase {
  
  generate(component: ComponentMetadata): string {
    const className = component.name;
    const tagName = this.toKebabCase(component.name);

    return `
// Auto-generated by Anto Studios Component Export
// Framework: Web Components (Vanilla JS)
// Generated: ${new Date().toISOString()}

${this.generateStyles(component)}

class ${className} extends HTMLElement {
  static get observedAttributes() {
    return [${component.props.map(p => `'${p.name}'`).join(', ')}];
  }

  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
    this._state = {
      ${component.props.map(p => `${p.name}: ${this.formatPropValue(p.defaultValue)}`).join(',\n      ')}
    };
  }

  connectedCallback() {
    this.render();
  }

  attributeChangedCallback(name, oldValue, newValue) {
    if (oldValue !== newValue) {
      this._state[name] = newValue;
      this.render();
    }
  }

  // Getters for properties
${component.props.map(p => `  get ${p.name}() {
    return this._state.${p.name};
  }`).join('\n\n  ')}

  // Setters for properties
${component.props.map(p => `  set ${p.name}(value) {
    this._state.${p.name} = value;
    this.setAttribute('${p.name}', value);
  }`).join('\n\n  ')}

  render() {
    const className = \`${component.baseClassName}\${this._state.variant ? ' ' + this._state.variant : ''}\`.trim();
    
    this.shadowRoot.innerHTML = \`
      <style>
        ${this.escapeTemplateLiterals(component.styles?.content || '')}
      </style>
      <${component.htmlTag}
        class="\${className}"
        \${this._state.disabled ? 'disabled' : ''}
        part="button"
      >
        <slot></slot>
      </${component.htmlTag}>
    \`;

    // Add event listeners
    const button = this.shadowRoot.querySelector('${component.htmlTag}');
    if (button) {
      button.addEventListener('click', (e) => {
        this.dispatchEvent(new CustomEvent('click', {
          detail: { originalEvent: e },
          bubbles: true,
          composed: true
        }));
      });
    }
  }
}

customElements.define('${tagName}', ${className});

export { ${className} };
    `.trim();
  }

  private generateStyles(component: ComponentMetadata): string {
    const styles = component.styles?.content || `.${component.baseClassName} {
  display: inline-block;
  padding: 0.5rem 1rem;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 1rem;
}`;

    return `
// Component styles
const styles = \`
${styles}
\`;
    `.trim();
  }

  private escapeTemplateLiterals(content: string): string {
    return content
      .replace(/\\/g, '\\\\')
      .replace(/\$/g, '\\
}
)
      .replace(/[\n]/g, '\n      ');
  }
}
