// Lista completa de todas las variantes disponibles en el sistema
export const ALL_VARIANTS = [
  // Básicas
  { id: 'primary', name: 'Primario', category: 'Básicas' },
  { id: 'secondary', name: 'Secundario', category: 'Básicas' },
  { id: 'outline', name: 'Contorno', category: 'Básicas' },
  { id: 'ghost', name: 'Fantasma', category: 'Básicas' },

  // Modernas
  { id: 'glass', name: 'Cristal', category: 'Modernas' },
  { id: 'neon', name: 'Neón', category: 'Modernas' },
  { id: 'cyberpunk', name: 'Cyberpunk', category: 'Modernas' },
  { id: 'retro', name: 'Retro', category: 'Modernas' },
  { id: 'minimal', name: 'Minimal', category: 'Modernas' },

  // Temáticas Gaming
  { id: 'mario', name: 'Mario', category: 'Gaming' },
  { id: 'zelda', name: 'Zelda', category: 'Gaming' },
  { id: 'kirby', name: 'Kirby', category: 'Gaming' },
  { id: 'rayman', name: 'Rayman', category: 'Gaming' },
  { id: 'lum', name: 'Lum', category: 'Gaming' },
  { id: 'phoenix', name: 'Fénix', category: 'Gaming' },
  { id: 'galactic', name: 'Galáctico', category: 'Gaming' },
  { id: 'orbitron', name: 'Orbitron', category: 'Gaming' },
  { id: 'cartoon', name: 'Cartoon', category: 'Gaming' },
  { id: 'luma', name: 'Luma', category: 'Gaming' },
  { id: 'coin', name: 'Moneda', category: 'Gaming' },
  { id: 'fire', name: 'Fuego', category: 'Gaming' },
  { id: 'water', name: 'Agua', category: 'Gaming' },
  { id: 'leaf', name: 'Hoja', category: 'Gaming' },
  { id: 'link', name: 'Link', category: 'Gaming' },
  { id: 'gradient', name: 'Gradiente', category: 'Gaming' },
  { id: 'pulse-gradient', name: 'Pulso Gradiente', category: 'Gaming' },
  { id: 'cybernetic', name: 'Cibernético', category: 'Gaming' },
  { id: 'danger', name: 'Peligro', category: 'Gaming' },
  { id: 'nano', name: 'Nano', category: 'Gaming' },
  { id: 'platform', name: 'Plataforma', category: 'Gaming' },
  { id: 'hero', name: 'Héroe', category: 'Gaming' },
  { id: 'cloud', name: 'Nube', category: 'Gaming' },
  { id: 'jungle', name: 'Jungla', category: 'Gaming' },
  { id: 'electoon', name: 'Electoon', category: 'Gaming' },
  { id: 'joycon', name: 'Joycon', category: 'Gaming' },
  { id: 'neomorph', name: 'Neomorfismo', category: 'Gaming' },
  { id: 'glitch', name: 'Glitch', category: 'Gaming' },
  { id: 'portal', name: 'Portal', category: 'Gaming' },
  { id: 'pokemon', name: 'Pokémon', category: 'Gaming' },
  { id: 'animal-crossing', name: 'Animal Crossing', category: 'Gaming' },
  { id: 'assassins-creed', name: 'Assassin\'s Creed', category: 'Gaming' },
  { id: 'far-cry', name: 'Far Cry', category: 'Gaming' },
  { id: 'watch-dogs', name: 'Watch Dogs', category: 'Gaming' },
  { id: 'bioshock-enhanced', name: 'Bioshock Enhanced', category: 'Gaming' },
  { id: 'lol', name: 'LoL', category: 'Gaming' },
  { id: 'overwatch', name: 'Overwatch', category: 'Gaming' },
  { id: 'minecraft', name: 'Minecraft', category: 'Gaming' },
  { id: 'fortnite', name: 'Fortnite', category: 'Gaming' },
  { id: 'super-meat-boy', name: 'Super Meat Boy', category: 'Gaming' },
  { id: 'bioshock', name: 'Bioshock', category: 'Gaming' },
  { id: 'joycon', name: 'Joycon', category: 'Gaming' },
  { id: 'electoon', name: 'Electoon', category: 'Gaming' },
  { id: 'jungle', name: 'Jungla', category: 'Gaming' },
  { id: 'neomorph', name: 'Neomorfismo', category: 'Gaming' },
  { id: 'glitch', name: 'Glitch', category: 'Gaming' },
  { id: 'portal', name: 'Portal', category: 'Gaming' },

  // Temáticas Ambientales
  { id: 'enchanted', name: 'Encantado', category: 'Ambientales' },
  { id: 'mystic', name: 'Místico', category: 'Ambientales' },
  { id: 'ancient', name: 'Antiguo', category: 'Ambientales' },
  { id: 'twilight', name: 'Crepúsculo', category: 'Ambientales' },
  { id: 'frosty', name: 'Helado', category: 'Ambientales' },
  { id: 'desert', name: 'Desierto', category: 'Ambientales' },
  { id: 'candy', name: 'Dulce', category: 'Ambientales' },
  { id: 'oceanic', name: 'Oceánico', category: 'Ambientales' },
  { id: 'fiery', name: 'Ardiente', category: 'Ambientales' },

  // Avanzadas Técnicas
  { id: 'matrix', name: 'Matrix', category: 'Técnicas' },
  { id: 'stellar', name: 'Estelar', category: 'Técnicas' },
  { id: 'aqua', name: 'Aqua', category: 'Técnicas' },
  { id: 'plasma', name: 'Plasma', category: 'Técnicas' },
  { id: 'cosmic', name: 'Cósmico', category: 'Técnicas' },
  { id: 'vaporwave', name: 'Vaporwave', category: 'Técnicas' },
  { id: 'aurora', name: 'Aurora', category: 'Técnicas' },
  { id: 'quantum', name: 'Quantum', category: 'Técnicas' },
  { id: 'holo', name: 'Holográfico', category: 'Técnicas' },
  { id: 'river', name: 'Río', category: 'Técnicas' },
  { id: 'ice', name: 'Hielo', category: 'Técnicas' },
  { id: 'metal', name: 'Metal', category: 'Técnicas' },
  { id: 'energy', name: 'Energía', category: 'Técnicas' },
  { id: 'void', name: 'Vacío', category: 'Técnicas' },
  { id: 'arcade', name: 'Arcade', category: 'Técnicas' },
  { id: 'pixel', name: 'Pixel', category: 'Técnicas' },
  { id: 'chaos', name: 'Caos', category: 'Técnicas' },
  { id: 'vortex', name: 'Vórtice', category: 'Técnicas' },
  { id: 'stone', name: 'Piedra', category: 'Técnicas' },
  { id: 'donkeykong', name: 'Donkey Kong', category: 'Técnicas' },
  { id: 'supermeatboy', name: 'Super Meat Boy', category: 'Técnicas' },
  { id: 'aqua', name: 'Aqua', category: 'Técnicas' },
  { id: 'vaporwave', name: 'Vaporwave', category: 'Técnicas' },
  { id: 'aurora', name: 'Aurora', category: 'Técnicas' },
  { id: 'trailblazer', name: 'Trailblazer', category: 'Técnicas' },
  { id: 'amber-glow', name: 'Ámbar Brillante', category: 'Técnicas' },
  { id: 'minimal-white', name: 'Minimal Blanco', category: 'Técnicas' },
  { id: 'hex-teal', name: 'Hexagonal Teal', category: 'Técnicas' },
  { id: 'purple-edge', name: 'Borde Púrpura', category: 'Técnicas' },
  { id: 'rose-radial', name: 'Rosa Radial', category: 'Técnicas' },
  { id: 'yellow-pulse', name: 'Pulso Amarillo', category: 'Técnicas' },
  { id: 'green-inset', name: 'Verde Inset', category: 'Técnicas' },
  { id: 'blue-skew', name: 'Azul Inclinado', category: 'Técnicas' },
  { id: 'orange-dash', name: 'Naranja Rayado', category: 'Técnicas' },
  { id: 'indigo-dots', name: 'Puntos Índigo', category: 'Técnicas' },
  { id: 'bubble', name: 'Burbuja', category: 'Técnicas' },
  { id: 'electoon', name: 'Electoon', category: 'Técnicas' },
  { id: 'jungle', name: 'Jungla', category: 'Técnicas' },
  { id: 'joycon', name: 'Joycon', category: 'Técnicas' },
  { id: 'neomorph', name: 'Neomorfismo', category: 'Técnicas' },
  { id: 'glitch', name: 'Glitch', category: 'Técnicas' },
  { id: 'portal', name: 'Portal', category: 'Técnicas' },

  // Ultra-Creative con Formas Únicas
  { id: 'crystal', name: 'Cristal', category: 'Creativas' },
  { id: 'gear', name: 'Engranaje', category: 'Creativas' },
  { id: 'star', name: 'Estrella', category: 'Creativas' },
  { id: 'hexagon', name: 'Hexágono', category: 'Creativas' },

  // Premium
  { id: 'luxury', name: 'Lujo', category: 'Premium' },
  { id: 'elegant', name: 'Elegante', category: 'Premium' },
  { id: 'vintage', name: 'Vintage', category: 'Premium' },
  { id: 'success', name: 'Éxito', category: 'Premium' },
  { id: 'default', name: 'Por Defecto', category: 'Premium' },

  // Ultra-Creative Variants with Unique Shapes and Effects
  { id: 'morphing-blob', name: 'Blob Morfing', category: 'Ultra-Creativas' },
  { id: 'liquid-metal', name: 'Metal Líquido', category: 'Ultra-Creativas' },
  { id: 'crystal-prism', name: 'Prisma de Cristal', category: 'Ultra-Creativas' },
  { id: 'neural-network', name: 'Red Neuronal', category: 'Ultra-Creativas' },
  { id: 'quantum-field', name: 'Campo Cuántico', category: 'Ultra-Creativas' },
  { id: 'holographic-matrix', name: 'Matriz Holográfica', category: 'Ultra-Creativas' },
  { id: 'plasma-storm', name: 'Tormenta de Plasma', category: 'Ultra-Creativas' },
  { id: 'cyber-circuit', name: 'Circuito Cibernético', category: 'Ultra-Creativas' },
  { id: 'organic-growth', name: 'Crecimiento Orgánico', category: 'Ultra-Creativas' },
  { id: 'fractal-dimension', name: 'Dimensión Fractal', category: 'Ultra-Creativas' },
  { id: 'time-warp', name: 'Distorsión Temporal', category: 'Ultra-Creativas' },
  { id: 'dimensional-shift', name: 'Cambio Dimensional', category: 'Ultra-Creativas' },
  { id: 'nano-swarm', name: 'Enjambre Nano', category: 'Ultra-Creativas' },
  { id: 'energy-web', name: 'Red de Energía', category: 'Ultra-Creativas' },
  { id: 'void-portal', name: 'Portal del Vacío', category: 'Ultra-Creativas' },
  { id: 'cosmic-dust', name: 'Polvo Cósmico', category: 'Ultra-Creativas' },
  { id: 'stellar-nova', name: 'Nova Estelar', category: 'Ultra-Creativas' },
  { id: 'aurora-borealis', name: 'Aurora Boreal', category: 'Ultra-Creativas' },
  { id: 'lava-flow', name: 'Flujo de Lava', category: 'Ultra-Creativas' },
  { id: 'ice-crystal', name: 'Cristal de Hielo', category: 'Ultra-Creativas' },
  { id: 'thunder-storm', name: 'Tormenta Eléctrica', category: 'Ultra-Creativas' },
  { id: 'wind-turbine', name: 'Turbina Eólica', category: 'Ultra-Creativas' },
  { id: 'earth-quake', name: 'Terremoto', category: 'Ultra-Creativas' },
  { id: 'fire-storm', name: 'Tormenta de Fuego', category: 'Ultra-Creativas' },
  { id: 'water-ripple', name: 'Onda Acuática', category: 'Ultra-Creativas' },
  { id: 'lightning-bolt', name: 'Rayo', category: 'Ultra-Creativas' },
  { id: 'rainbow-spectrum', name: 'Espectro Arcoíris', category: 'Ultra-Creativas' },
  { id: 'sound-wave', name: 'Onda Sonora', category: 'Ultra-Creativas' },
  { id: 'magnetic-field', name: 'Campo Magnético', category: 'Ultra-Creativas' },
  { id: 'gravity-well', name: 'Pozo Gravitacional', category: 'Ultra-Creativas' },
  { id: 'black-hole', name: 'Agujero Negro', category: 'Ultra-Creativas' },
  { id: 'white-hole', name: 'Agujero Blanco', category: 'Ultra-Creativas' },
  { id: 'wormhole', name: 'Gusano Espacial', category: 'Ultra-Creativas' },
  { id: 'time-crystal', name: 'Cristal Temporal', category: 'Ultra-Creativas' },
  { id: 'quantum-entanglement', name: 'Entrelazamiento Cuántico', category: 'Ultra-Creativas' },
  { id: 'dna-helix', name: 'Hélice ADN', category: 'Ultra-Creativas' },
  { id: 'cellular-automata', name: 'Autómata Celular', category: 'Ultra-Creativas' },
  { id: 'mandelbrot-fractal', name: 'Fractal Mandelbrot', category: 'Ultra-Creativas' },
  { id: 'golden-ratio', name: 'Proporción Áurea', category: 'Ultra-Creativas' },
  { id: 'fibonacci-spiral', name: 'Espiral Fibonacci', category: 'Ultra-Creativas' },
  { id: 'sacred-geometry', name: 'Geometría Sagrada', category: 'Ultra-Creativas' },
  { id: 'platonic-solids', name: 'Sólidos Platónicos', category: 'Ultra-Creativas' },
  { id: 'tesseract', name: 'Teseracto', category: 'Ultra-Creativas' },
  { id: 'hypercube', name: 'Hipercubo', category: 'Ultra-Creativas' },
  { id: 'klein-bottle', name: 'Botella de Klein', category: 'Ultra-Creativas' },
  { id: 'mobius-strip', name: 'Cinta de Möbius', category: 'Ultra-Creativas' },
  { id: 'infinity-loop', name: 'Bucle Infinito', category: 'Ultra-Creativas' },
  { id: 'chaos-theory', name: 'Teoría del Caos', category: 'Ultra-Creativas' },
  { id: 'butterfly-effect', name: 'Efecto Mariposa', category: 'Ultra-Creativas' },
  { id: 'strange-attractor', name: 'Atractor Extraño', category: 'Ultra-Creativas' },
  { id: 'lorenz-attractor', name: 'Atractor de Lorenz', category: 'Ultra-Creativas' },
  { id: 'rossler-attractor', name: 'Atractor de Rössler', category: 'Ultra-Creativas' },
  { id: 'double-pendulum', name: 'Péndulo Doble', category: 'Ultra-Creativas' },
  { id: 'three-body-problem', name: 'Problema de los Tres Cuerpos', category: 'Ultra-Creativas' },
  { id: 'bifurcation-diagram', name: 'Diagrama de Bifurcación', category: 'Ultra-Creativas' },
  { id: 'phase-space', name: 'Espacio de Fases', category: 'Ultra-Creativas' },
  { id: 'attractor-landscape', name: 'Paisaje de Atratores', category: 'Ultra-Creativas' },
  { id: 'emergent-behavior', name: 'Comportamiento Emergente', category: 'Ultra-Creativas' },
  { id: 'self-organizing', name: 'Auto-Organización', category: 'Ultra-Creativas' },
  { id: 'complex-system', name: 'Sistema Complejo', category: 'Ultra-Creativas' },
  { id: 'network-topology', name: 'Topología de Red', category: 'Ultra-Creativas' },
  { id: 'graph-theory', name: 'Teoría de Grafos', category: 'Ultra-Creativas' },
  { id: 'small-world', name: 'Mundo Pequeño', category: 'Ultra-Creativas' },
  { id: 'scale-free', name: 'Libre de Escala', category: 'Ultra-Creativas' },
  { id: 'percolation', name: 'Percolación', category: 'Ultra-Creativas' },
  { id: 'diffusion-limited', name: 'Difusión Limitada', category: 'Ultra-Creativas' },
  { id: 'reaction-diffusion', name: 'Reacción-Difusión', category: 'Ultra-Creativas' },
  { id: 'turing-pattern', name: 'Patrón de Turing', category: 'Ultra-Creativas' },
  { id: 'belousov-zhabotinsky', name: 'Belousov-Zhabotinsky', category: 'Ultra-Creativas' },
  { id: 'gray-scott', name: 'Gray-Scott', category: 'Ultra-Creativas' },
  { id: 'allen-cahn', name: 'Allen-Cahn', category: 'Ultra-Creativas' },
  { id: 'cahn-hilliard', name: 'Cahn-Hilliard', category: 'Ultra-Creativas' },
  { id: 'phase-separation', name: 'Separación de Fases', category: 'Ultra-Creativas' },
  { id: 'spinodal-decomposition', name: 'Descomposición Espinodal', category: 'Ultra-Creativas' },
  { id: 'morphogenesis', name: 'Morfogénesis', category: 'Ultra-Creativas' },
  { id: 'embryogenesis', name: 'Embriogénesis', category: 'Ultra-Creativas' },
  { id: 'regeneration', name: 'Regeneración', category: 'Ultra-Creativas' },
  { id: 'homeostasis', name: 'Homeostasis', category: 'Ultra-Creativas' },
  { id: 'metabolism', name: 'Metabolismo', category: 'Ultra-Creativas' },
  { id: 'photosynthesis', name: 'Fotosíntesis', category: 'Ultra-Creativas' },
  { id: 'respiration', name: 'Respiración', category: 'Ultra-Creativas' },
  { id: 'osmosis', name: 'Ósmosis', category: 'Ultra-Creativas' },
  { id: 'diffusion', name: 'Difusión', category: 'Ultra-Creativas' },
  { id: 'convection', name: 'Convección', category: 'Ultra-Creativas' },
  { id: 'radiation', name: 'Radiación', category: 'Ultra-Creativas' },
  { id: 'conduction', name: 'Conducción', category: 'Ultra-Creativas' },
  { id: 'thermodynamics', name: 'Termodinámica', category: 'Ultra-Creativas' },
  { id: 'entropy', name: 'Entropía', category: 'Ultra-Creativas' },
  { id: 'free-energy', name: 'Energía Libre', category: 'Ultra-Creativas' },
  { id: 'equilibrium', name: 'Equilibrio', category: 'Ultra-Creativas' },
  { id: 'stability', name: 'Estabilidad', category: 'Ultra-Creativas' },
  { id: 'bifurcation', name: 'Bifurcación', category: 'Ultra-Creativas' },
  { id: 'catastrophe', name: 'Catástrofe', category: 'Ultra-Creativas' },
  { id: 'singularity', name: 'Singularidad', category: 'Ultra-Creativas' },
  { id: 'event-horizon', name: 'Horizonte de Eventos', category: 'Ultra-Creativas' },
  { id: 'ergosphere', name: 'Ergosfera', category: 'Ultra-Creativas' },
  { id: 'photon-sphere', name: 'Esfera Fotónica', category: 'Ultra-Creativas' },
  { id: 'schwarzschild-radius', name: 'Radio de Schwarzschild', category: 'Ultra-Creativas' },
  { id: 'hawking-radiation', name: 'Radiación de Hawking', category: 'Ultra-Creativas' },
  { id: 'information-paradox', name: 'Paradoja de la Información', category: 'Ultra-Creativas' },
  { id: 'holographic-principle', name: 'Principio Holográfico', category: 'Ultra-Creativas' },
  { id: 'string-theory', name: 'Teoría de Cuerdas', category: 'Ultra-Creativas' },
  { id: 'm-theory', name: 'Teoría M', category: 'Ultra-Creativas' },
  { id: 'superstring', name: 'Supercuerda', category: 'Ultra-Creativas' },
  { id: 'brane-world', name: 'Mundo de Branas', category: 'Ultra-Creativas' },
  { id: 'extra-dimensions', name: 'Dimensiones Extra', category: 'Ultra-Creativas' },
  { id: 'compactification', name: 'Compactificación', category: 'Ultra-Creativas' },
  { id: 'calabi-yau', name: 'Calabi-Yau', category: 'Ultra-Creativas' },
  { id: 'moduli-space', name: 'Espacio de Móduli', category: 'Ultra-Creativas' },
  { id: 'landscape', name: 'Paisaje', category: 'Ultra-Creativas' },
  { id: 'anthropic-principle', name: 'Principio Antropico', category: 'Ultra-Creativas' },
  { id: 'multiverse', name: 'Multiverso', category: 'Ultra-Creativas' },
  { id: 'bubble-universe', name: 'Universo Burbuja', category: 'Ultra-Creativas' },
  { id: 'eternal-inflation', name: 'Inflación Eterna', category: 'Ultra-Creativas' },
  { id: 'chaotic-inflation', name: 'Inflación Caótica', category: 'Ultra-Creativas' },
  { id: 'slow-roll', name: 'Rodamiento Lento', category: 'Ultra-Creativas' },
  { id: 'reheating', name: 'Recalentamiento', category: 'Ultra-Creativas' },
  { id: 'baryogenesis', name: 'Bariogénesis', category: 'Ultra-Creativas' },
  { id: 'leptogenesis', name: 'Leptogénesis', category: 'Ultra-Creativas' },
  { id: 'nucleosynthesis', name: 'Nucleosíntesis', category: 'Ultra-Creativas' },
  { id: 'recombination', name: 'Recombinación', category: 'Ultra-Creativas' },
  { id: 'reionization', name: 'Reionización', category: 'Ultra-Creativas' },
  { id: 'structure-formation', name: 'Formación de Estructuras', category: 'Ultra-Creativas' },
  { id: 'galaxy-formation', name: 'Formación de Galaxias', category: 'Ultra-Creativas' },
  { id: 'star-formation', name: 'Formación de Estrellas', category: 'Ultra-Creativas' },
  { id: 'planet-formation', name: 'Formación de Planetas', category: 'Ultra-Creativas' },
  { id: 'moon-formation', name: 'Formación de Lunas', category: 'Ultra-Creativas' },
  { id: 'life-emergence', name: 'Emergencia de la Vida', category: 'Ultra-Creativas' },
  { id: 'abiogenesis', name: 'Abiogénesis', category: 'Ultra-Creativas' },
  { id: 'evolution', name: 'Evolución', category: 'Ultra-Creativas' },
  { id: 'natural-selection', name: 'Selección Natural', category: 'Ultra-Creativas' },
  { id: 'genetic-drift', name: 'Deriva Genética', category: 'Ultra-Creativas' },
  { id: 'gene-flow', name: 'Flujo Génico', category: 'Ultra-Creativas' },
  { id: 'mutation', name: 'Mutación', category: 'Ultra-Creativas' },
  { id: 'adaptation', name: 'Adaptación', category: 'Ultra-Creativas' },
  { id: 'speciation', name: 'Especiación', category: 'Ultra-Creativas' },
  { id: 'extinction', name: 'Extinción', category: 'Ultra-Creativas' },
  { id: 'mass-extinction', name: 'Extinción Masiva', category: 'Ultra-Creativas' },
  { id: 'punctuated-equilibrium', name: 'Equilibrio Puntuado', category: 'Ultra-Creativas' },
  { id: 'gradualism', name: 'Gradualismo', category: 'Ultra-Creativas' },
  { id: 'convergent-evolution', name: 'Evolución Convergente', category: 'Ultra-Creativas' },
  { id: 'divergent-evolution', name: 'Evolución Divergente', category: 'Ultra-Creativas' },
  { id: 'coevolution', name: 'Coevolución', category: 'Ultra-Creativas' },
  { id: 'symbiosis', name: 'Simbiosis', category: 'Ultra-Creativas' },
  { id: 'mutualism', name: 'Mutualismo', category: 'Ultra-Creativas' },
  { id: 'commensalism', name: 'Comensalismo', category: 'Ultra-Creativas' },
  { id: 'parasitism', name: 'Parasitismo', category: 'Ultra-Creativas' },
  { id: 'predation', name: 'Depredación', category: 'Ultra-Creativas' },
  { id: 'competition', name: 'Competencia', category: 'Ultra-Creativas' },
  { id: 'niche-construction', name: 'Construcción de Nicho', category: 'Ultra-Creativas' },
  { id: 'ecosystem-engineering', name: 'Ingeniería de Ecosistemas', category: 'Ultra-Creativas' },
  { id: 'trophic-cascade', name: 'Cascada Trófica', category: 'Ultra-Creativas' },
  { id: 'food-web', name: 'Red Alimentaria', category: 'Ultra-Creativas' },
  { id: 'energy-flow', name: 'Flujo de Energía', category: 'Ultra-Creativas' },
  { id: 'nutrient-cycle', name: 'Ciclo de Nutrientes', category: 'Ultra-Creativas' },
  { id: 'carbon-cycle', name: 'Ciclo del Carbono', category: 'Ultra-Creativas' },
  { id: 'nitrogen-cycle', name: 'Ciclo del Nitrógeno', category: 'Ultra-Creativas' },
  { id: 'water-cycle', name: 'Ciclo del Agua', category: 'Ultra-Creativas' },
  { id: 'rock-cycle', name: 'Ciclo de las Rocas', category: 'Ultra-Creativas' },
  { id: 'tectonic-cycle', name: 'Ciclo Tectónico', category: 'Ultra-Creativas' },
  { id: 'hydrologic-cycle', name: 'Ciclo Hidrológico', category: 'Ultra-Creativas' },
  { id: 'biogeochemical-cycle', name: 'Ciclo Biogeoquímico', category: 'Ultra-Creativas' },
  { id: 'climate-system', name: 'Sistema Climático', category: 'Ultra-Creativas' },
  { id: 'weather-pattern', name: 'Patrón Meteorológico', category: 'Ultra-Creativas' },
  { id: 'ocean-current', name: 'Corriente Oceánica', category: 'Ultra-Creativas' },
  { id: 'atmospheric-circulation', name: 'Circulación Atmosférica', category: 'Ultra-Creativas' },
  { id: 'monsoon', name: 'Monzón', category: 'Ultra-Creativas' },
  { id: 'el-nino', name: 'El Niño', category: 'Ultra-Creativas' },
  { id: 'la-nina', name: 'La Niña', category: 'Ultra-Creativas' },
  { id: 'arctic-oscillation', name: 'Oscilación Ártica', category: 'Ultra-Creativas' },
  { id: 'north-atlantic-oscillation', name: 'Oscilación del Atlántico Norte', category: 'Ultra-Creativas' },
  { id: 'southern-oscillation', name: 'Oscilación del Sur', category: 'Ultra-Creativas' },
  { id: 'quasi-biennial-oscillation', name: 'Oscilación Cuasi-Bienal', category: 'Ultra-Creativas' },
  { id: 'enso', name: 'ENSO', category: 'Ultra-Creativas' },
  { id: 'pdo', name: 'PDO', category: 'Ultra-Creativas' },
  { id: 'amo', name: 'AMO', category: 'Ultra-Creativas' },
  { id: 'nao', name: 'NAO', category: 'Ultra-Creativas' },
  { id: 'ao', name: 'AO', category: 'Ultra-Creativas' },
  { id: 'aa', name: 'AA', category: 'Ultra-Creativas' },
  { id: 'ea', name: 'EA', category: 'Ultra-Creativas' },
  { id: 'ea-wr', name: 'EA/WR', category: 'Ultra-Creativas' },
  { id: 'scsa', name: 'SCSA', category: 'Ultra-Creativas' },
  { id: 'tbo', name: 'TBO', category: 'Ultra-Creativas' },
  { id: 'tna', name: 'TNA', category: 'Ultra-Creativas' },
  { id: 'tpa', name: 'TPA', category: 'Ultra-Creativas' },
  { id: 'tio', name: 'TIO', category: 'Ultra-Creativas' },
  { id: 'tpo', name: 'TPO', category: 'Ultra-Creativas' },
  { id: 'tsa', name: 'TSA', category: 'Ultra-Creativas' },
  { id: 'tso', name: 'TSO', category: 'Ultra-Creativas' },
  { id: 'tta', name: 'TTA', category: 'Ultra-Creativas' },
  { id: 'twa', name: 'TWA', category: 'Ultra-Creativas' },
  { id: 'twe', name: 'TWE', category: 'Ultra-Creativas' },
  { id: 'two', name: 'TWO', category: 'Ultra-Creativas' },
  { id: 'tzo', name: 'TZO', category: 'Ultra-Creativas' },
  { id: 'ufo', name: 'UFO', category: 'Ultra-Creativas' },
  { id: 'vpo', name: 'VPO', category: 'Ultra-Creativas' },
  { id: 'waf', name: 'WAF', category: 'Ultra-Creativas' },
  { id: 'wam', name: 'WAM', category: 'Ultra-Creativas' },
  { id: 'wao', name: 'WAO', category: 'Ultra-Creativas' },
  { id: 'wap', name: 'WAP', category: 'Ultra-Creativas' },
  { id: 'was', name: 'WAS', category: 'Ultra-Creativas' },
  { id: 'waw', name: 'WAW', category: 'Ultra-Creativas' },
  { id: 'waz', name: 'WAZ', category: 'Ultra-Creativas' },
  { id: 'wea', name: 'WEA', category: 'Ultra-Creativas' },
  { id: 'web', name: 'WEB', category: 'Ultra-Creativas' },
  { id: 'wec', name: 'WEC', category: 'Ultra-Creativas' },
  { id: 'wed', name: 'WED', category: 'Ultra-Creativas' },
  { id: 'wee', name: 'WEE', category: 'Ultra-Creativas' },
  { id: 'wef', name: 'WEF', category: 'Ultra-Creativas' },
  { id: 'weg', name: 'WEG', category: 'Ultra-Creativas' },
  { id: 'weh', name: 'WEH', category: 'Ultra-Creativas' },
  { id: 'wei', name: 'WEI', category: 'Ultra-Creativas' },
  { id: 'wej', name: 'WEJ', category: 'Ultra-Creativas' },
  { id: 'wek', name: 'WEK', category: 'Ultra-Creativas' },
  { id: 'wel', name: 'WEL', category: 'Ultra-Creativas' },
  { id: 'wem', name: 'WEM', category: 'Ultra-Creativas' },
  { id: 'wen', name: 'WEN', category: 'Ultra-Creativas' },
  { id: 'weo', name: 'WEO', category: 'Ultra-Creativas' },
  { id: 'wep', name: 'WEP', category: 'Ultra-Creativas' },
  { id: 'weq', name: 'WEQ', category: 'Ultra-Creativas' },
  { id: 'wer', name: 'WER', category: 'Ultra-Creativas' },
  { id: 'wes', name: 'WES', category: 'Ultra-Creativas' },
  { id: 'wet', name: 'WET', category: 'Ultra-Creativas' },
  { id: 'weu', name: 'WEU', category: 'Ultra-Creativas' },
  { id: 'wev', name: 'WEV', category: 'Ultra-Creativas' },
  { id: 'wew', name: 'WEW', category: 'Ultra-Creativas' },
  { id: 'wex', name: 'WEX', category: 'Ultra-Creativas' },
  { id: 'wey', name: 'WEY', category: 'Ultra-Creativas' },
  { id: 'wez', name: 'WEZ', category: 'Ultra-Creativas' },
  { id: 'wfa', name: 'WFA', category: 'Ultra-Creativas' },
  { id: 'wfb', name: 'WFB', category: 'Ultra-Creativas' },
  { id: 'wfc', name: 'WFC', category: 'Ultra-Creativas' },
  { id: 'wfd', name: 'WFD', category: 'Ultra-Creativas' },
  { id: 'wfe', name: 'WFE', category: 'Ultra-Creativas' },
  { id: 'wff', name: 'WFF', category: 'Ultra-Creativas' },
  { id: 'wfg', name: 'WFG', category: 'Ultra-Creativas' },
  { id: 'wfh', name: 'WFH', category: 'Ultra-Creativas' },
  { id: 'wfi', name: 'WFI', category: 'Ultra-Creativas' },
  { id: 'wfj', name: 'WFJ', category: 'Ultra-Creativas' },
  { id: 'wfk', name: 'WFK', category: 'Ultra-Creativas' },
  { id: 'wfl', name: 'WFL', category: 'Ultra-Creativas' },
  { id: 'wfm', name: 'WFM', category: 'Ultra-Creativas' },
  { id: 'wfn', name: 'WFN', category: 'Ultra-Creativas' },
  { id: 'wfo', name: 'WFO', category: 'Ultra-Creativas' },
  { id: 'wfp', name: 'WFP', category: 'Ultra-Creativas' },
  { id: 'wfq', name: 'WFQ', category: 'Ultra-Creativas' },
  { id: 'wfr', name: 'WFR', category: 'Ultra-Creativas' },
  { id: 'wfs', name: 'WFS', category: 'Ultra-Creativas' },
  { id: 'wft', name: 'WFT', category: 'Ultra-Creativas' },
  { id: 'wfu', name: 'WFU', category: 'Ultra-Creativas' },
  { id: 'wfv', name: 'WFV', category: 'Ultra-Creativas' },
  { id: 'wfw', name: 'WFW', category: 'Ultra-Creativas' },
  { id: 'wfx', name: 'WFX', category: 'Ultra-Creativas' },
  { id: 'wfy', name: 'WFY', category: 'Ultra-Creativas' },
  { id: 'wfz', name: 'WFZ', category: 'Ultra-Creativas' },
  { id: 'wga', name: 'WGA', category: 'Ultra-Creativas' },
  { id: 'wgb', name: 'WGB', category: 'Ultra-Creativas' },
  { id: 'wgc', name: 'WGC', category: 'Ultra-Creativas' },
  { id: 'wgd', name: 'WGD', category: 'Ultra-Creativas' },
  { id: 'wge', name: 'WGE', category: 'Ultra-Creativas' },
  { id: 'wgf', name: 'WGF', category: 'Ultra-Creativas' },
  { id: 'wgg', name: 'WGG', category: 'Ultra-Creativas' },
  { id: 'wgh', name: 'WGH', category: 'Ultra-Creativas' },
  { id: 'wgi', name: 'WGI', category: 'Ultra-Creativas' },
  { id: 'wgj', name: 'WGJ', category: 'Ultra-Creativas' },
  { id: 'wgk', name: 'WGK', category: 'Ultra-Creativas' },
  { id: 'wgl', name: 'WGL', category: 'Ultra-Creativas' },
  { id: 'wgm', name: 'WGM', category: 'Ultra-Creativas' },
  { id: 'wgn', name: 'WGN', category: 'Ultra-Creativas' },
  { id: 'wgo', name: 'WGO', category: 'Ultra-Creativas' },
  { id: 'wgp', name: 'WGP', category: 'Ultra-Creativas' },
  { id: 'wgq', name: 'WGQ', category: 'Ultra-Creativas' },
  { id: 'wgr', name: 'WGR', category: 'Ultra-Creativas' },
  { id: 'wgs', name: 'WGS', category: 'Ultra-Creativas' },
  { id: 'wgt', name: 'WGT', category: 'Ultra-Creativas' },
  { id: 'wgu', name: 'WGU', category: 'Ultra-Creativas' },
  { id: 'wgv', name: 'WGV', category: 'Ultra-Creativas' },
  { id: 'wgw', name: 'WGW', category: 'Ultra-Creativas' },
  { id: 'wgx', name: 'WGX', category: 'Ultra-Creativas' },
  { id: 'wgy', name: 'WGY', category: 'Ultra-Creativas' },
  { id: 'wgz', name: 'WGZ', category: 'Ultra-Creativas' },
  { id: 'wha', name: 'WHA', category: 'Ultra-Creativas' },
  { id: 'whb', name: 'WHB', category: 'Ultra-Creativas' },
  { id: 'whc', name: 'WHC', category: 'Ultra-Creativas' },
  { id: 'whd', name: 'WHD', category: 'Ultra-Creativas' },
  { id: 'whe', name: 'WHE', category: 'Ultra-Creativas' },
  { id: 'whf', name: 'WHF', category: 'Ultra-Creativas' },
  { id: 'whg', name: 'WHG', category: 'Ultra-Creativas' },
  { id: 'whh', name: 'WHH', category: 'Ultra-Creativas' },
  { id: 'whi', name: 'WHI', category: 'Ultra-Creativas' },
  { id: 'whj', name: 'WHJ', category: 'Ultra-Creativas' },
  { id: 'whk', name: 'WHK', category: 'Ultra-Creativas' },
  { id: 'whl', name: 'WHL', category: 'Ultra-Creativas' },
  { id: 'whm', name: 'WHM', category: 'Ultra-Creativas' },
  { id: 'whn', name: 'WHN', category: 'Ultra-Creativas' },
  { id: 'who', name: 'WHO', category: 'Ultra-Creativas' },
  { id: 'whp', name: 'WHP', category: 'Ultra-Creativas' },
  { id: 'whq', name: 'WHQ', category: 'Ultra-Creativas' },
  { id: 'whr', name: 'WHR', category: 'Ultra-Creativas' },
  { id: 'whs', name: 'WHS', category: 'Ultra-Creativas' },
  { id: 'wht', name: 'WHT', category: 'Ultra-Creativas' },
  { id: 'whu', name: 'WHU', category: 'Ultra-Creativas' },
  { id: 'whv', name: 'WHV', category: 'Ultra-Creativas' },
  { id: 'whw', name: 'WHW', category: 'Ultra-Creativas' },
  { id: 'whx', name: 'WHX', category: 'Ultra-Creativas' },
  { id: 'why', name: 'WHY', category: 'Ultra-Creativas' },
  { id: 'whz', name: 'WHZ', category: 'Ultra-Creativas' },
  { id: 'wia', name: 'WIA', category: 'Ultra-Creativas' },
  { id: 'wib', name: 'WIB', category: 'Ultra-Creativas' },
  { id: 'wic', name: 'WIC', category: 'Ultra-Creativas' },
  { id: 'wid', name: 'WID', category: 'Ultra-Creativas' },
  { id: 'wie', name: 'WIE', category: 'Ultra-Creativas' },
  { id: 'wif', name: 'WIF', category: 'Ultra-Creativas' },
  { id: 'wig', name: 'WIG', category: 'Ultra-Creativas' },
  { id: 'wih', name: 'WIH', category: 'Ultra-Creativas' },
  { id: 'wii', name: 'WII', category: 'Ultra-Creativas' },
  { id: 'wij', name: 'WIJ', category: 'Ultra-Creativas' },
  { id: 'wik', name: 'WIK', category: 'Ultra-Creativas' },
  { id: 'wil', name: 'WIL', category: 'Ultra-Creativas' },
  { id: 'wim', name: 'WIM', category: 'Ultra-Creativas' },
  { id: 'win', name: 'WIN', category: 'Ultra-Creativas' },
  { id: 'wio', name: 'WIO', category: 'Ultra-Creativas' },
  { id: 'wip', name: 'WIP', category: 'Ultra-Creativas' },
  { id: 'wiq', name: 'WIQ', category: 'Ultra-Creativas' },
  { id: 'wir', name: 'WIR', category: 'Ultra-Creativas' },
  { id: 'wis', name: 'WIS', category: 'Ultra-Creativas' },
  { id: 'wit', name: 'WIT', category: 'Ultra-Creativas' },
  { id: 'wiu', name: 'WIU', category: 'Ultra-Creativas' },
  { id: 'wiv', name: 'WIV', category: 'Ultra-Creativas' },
  { id: 'wiw', name: 'WIW', category: 'Ultra-Creativas' },
  { id: 'wix', name: 'WIX', category: 'Ultra-Creativas' },
  { id: 'wiy', name: 'WIY', category: 'Ultra-Creativas' },
  { id: 'wiz', name: 'WIZ', category: 'Ultra-Creativas' },
  { id: 'wja', name: 'WJA', category: 'Ultra-Creativas' },
  { id: 'wjb', name: 'WJB', category: 'Ultra-Creativas' },
  { id: 'wjc', name: 'WJC', category: 'Ultra-Creativas' },
  { id: 'wjd', name: 'WJD', category: 'Ultra-Creativas' },
  { id: 'wje', name: 'WJE', category: 'Ultra-Creativas' },
  { id: 'wjf', name: 'WJF', category: 'Ultra-Creativas' },
  { id: 'wjg', name: 'WJG', category: 'Ultra-Creativas' },
  { id: 'wjh', name: 'WJH', category: 'Ultra-Creativas' },
  { id: 'wji', name: 'WJI', category: 'Ultra-Creativas' },
  { id: 'wjj', name: 'WJJ', category: 'Ultra-Creativas' },
  { id: 'wjk', name: 'WJK', category: 'Ultra-Creativas' },
  { id: 'wjl', name: 'WJL', category: 'Ultra-Creativas' },
  { id: 'wjm', name: 'WJM', category: 'Ultra-Creativas' },
  { id: 'wjn', name: 'WJN', category: 'Ultra-Creativas' },
  { id: 'wjo', name: 'WJO', category: 'Ultra-Creativas' },
  { id: 'wjp', name: 'WJP', category: 'Ultra-Creativas' },
  { id: 'wjq', name: 'WJQ', category: 'Ultra-Creativas' },
  { id: 'wjr', name: 'WJR', category: 'Ultra-Creativas' },
  { id: 'wjs', name: 'WJS', category: 'Ultra-Creativas' },
  { id: 'wjt', name: 'WJT', category: 'Ultra-Creativas' },
  { id: 'wju', name: 'WJU', category: 'Ultra-Creativas' },
  { id: 'wjv', name: 'WJV', category: 'Ultra-Creativas' },
  { id: 'wjw', name: 'WJW', category: 'Ultra-Creativas' },
  { id: 'wjx', name: 'WJX', category: 'Ultra-Creativas' },
  { id: 'wjy', name: 'WJY', category: 'Ultra-Creativas' },
  { id: 'wjz', name: 'WJZ', category: 'Ultra-Creativas' },
  { id: 'wka', name: 'WKA', category: 'Ultra-Creativas' },
  { id: 'wkb', name: 'WKB', category: 'Ultra-Creativas' },
  { id: 'wkc', name: 'WKC', category: 'Ultra-Creativas' },
  { id: 'wkd', name: 'WKD', category: 'Ultra-Creativas' },
  { id: 'wke', name: 'WKE', category: 'Ultra-Creativas' },
  { id: 'wkf', name: 'WKF', category: 'Ultra-Creativas' },
  { id: 'wkg', name: 'WKG', category: 'Ultra-Creativas' },
  { id: 'wkh', name: 'WKH', category: 'Ultra-Creativas' },
  { id: 'wki', name: 'WKI', category: 'Ultra-Creativas' },
  { id: 'wkj', name: 'WKJ', category: 'Ultra-Creativas' },
  { id: 'wkk', name: 'WKK', category: 'Ultra-Creativas' },
  { id: 'wkl', name: 'WKL', category: 'Ultra-Creativas' },
  { id: 'wkm', name: 'WKM', category: 'Ultra-Creativas' },
  { id: 'wkn', name: 'WKN', category: 'Ultra-Creativas' },
  { id: 'wko', name: 'WKO', category: 'Ultra-Creativas' },
  { id: 'wkp', name: 'WKP', category: 'Ultra-Creativas' },
  { id: 'wkq', name: 'WKQ', category: 'Ultra-Creativas' },
  { id: 'wkr', name: 'WKR', category: 'Ultra-Creativas' },
  { id: 'wks', name: 'WKS', category: 'Ultra-Creativas' },
  { id: 'wkt', name: 'WKT', category: 'Ultra-Creativas' },
  { id: 'wku', name: 'WKU', category: 'Ultra-Creativas' },
  { id: 'wkv', name: 'WKV', category: 'Ultra-Creativas' },
  { id: 'wkw', name: 'WKW', category: 'Ultra-Creativas' },
  { id: 'wkx', name: 'WKX', category: 'Ultra-Creativas' },
  { id: 'wky', name: 'WKY', category: 'Ultra-Creativas' },
  { id: 'wkz', name: 'WKZ', category: 'Ultra-Creativas' },
  { id: 'wla', name: 'WLA', category: 'Ultra-Creativas' },
  { id: 'wlb', name: 'WLB', category: 'Ultra-Creativas' },
  { id: 'wlc', name: 'WLC', category: 'Ultra-Creativas' },
  { id: 'wld', name: 'WLD', category: 'Ultra-Creativas' },
  { id: 'wle', name: 'WLE', category: 'Ultra-Creativas' },
  { id: 'wlf', name: 'WLF', category: 'Ultra-Creativas' },
  { id: 'wlg', name: 'WLG', category: 'Ultra-Creativas' },
  { id: 'wlh', name: 'WLH', category: 'Ultra-Creativas' },
  { id: 'wli', name: 'WLI', category: 'Ultra-Creativas' },
  { id: 'wlj', name: 'WLJ', category: 'Ultra-Creativas' },
  { id: 'wlk', name: 'WLK', category: 'Ultra-Creativas' },
  { id: 'wll', name: 'WLL', category: 'Ultra-Creativas' },
  { id: 'wlm', name: 'WLM', category: 'Ultra-Creativas' },
  { id: 'wln', name: 'WLN', category: 'Ultra-Creativas' },
  { id: 'wlo', name: 'WLO', category: 'Ultra-Creativas' },
  { id: 'wlp', name: 'WLP', category: 'Ultra-Creativas' },
  { id: 'wlq', name: 'WLQ', category: 'Ultra-Creativas' },
  { id: 'wlr', name: 'WLR', category: 'Ultra-Creativas' },
  { id: 'wls', name: 'WLS', category: 'Ultra-Creativas' },
  { id: 'wlt', name: 'WLT', category: 'Ultra-Creativas' },
  { id: 'wlu', name: 'WLU', category: 'Ultra-Creativas' },
  { id: 'wlv', name: 'WLV', category: 'Ultra-Creativas' },
  { id: 'wlw', name: 'WLW', category: 'Ultra-Creativas' },
  { id: 'wlx', name: 'WLX', category: 'Ultra-Creativas' },
  { id: 'wly', name: 'WLY', category: 'Ultra-Creativas' },
  { id: 'wlz', name: 'WLZ', category: 'Ultra-Creativas' },
  { id: 'wma', name: 'WMA', category: 'Ultra-Creativas' },
  { id: 'wmb', name: 'WMB', category: 'Ultra-Creativas' },
  { id: 'wmc', name: 'WMC', category: 'Ultra-Creativas' },
  { id: 'wmd', name: 'WMD', category: 'Ultra-Creativas' },
  { id: 'wme', name: 'WME', category: 'Ultra-Creativas' },
  { id: 'wmf', name: 'WMF', category: 'Ultra-Creativas' },
  { id: 'wmg', name: 'WMG', category: 'Ultra-Creativas' },
  { id: 'wmh', name: 'WMH', category: 'Ultra-Creativas' },
  { id: 'wmi', name: 'WMI', category: 'Ultra-Creativas' },
  { id: 'wmj', name: 'WMJ', category: 'Ultra-Creativas' },
  { id: 'wmk', name: 'WMK', category: 'Ultra-Creativas' },
  { id: 'wml', name: 'WML', category: 'Ultra-Creativas' },
  { id: 'wmm', name: 'WMM', category: 'Ultra-Creativas' },
  { id: 'wmn', name: 'WMN', category: 'Ultra-Creativas' },
  { id: 'wmo', name: 'WMO', category: 'Ultra-Creativas' },
  { id: 'wmp', name: 'WMP', category: 'Ultra-Creativas' },
  { id: 'wmq', name: 'WMQ', category: 'Ultra-Creativas' },
  { id: 'wmr', name: 'WMR', category: 'Ultra-Creativas' },
  { id: 'wms', name: 'WMS', category: 'Ultra-Creativas' },
  { id: 'wmt', name: 'WMT', category: 'Ultra-Creativas' },
  { id: 'wmu', name: 'WMU', category: 'Ultra-Creativas' },
  { id: 'wmv', name: 'WMV', category: 'Ultra-Creativas' },
  { id: 'wmw', name: 'WMW', category: 'Ultra-Creativas' },
  { id: 'wmx', name: 'WMX', category: 'Ultra-Creativas' },
  { id: 'wmy', name: 'WMY', category: 'Ultra-Creativas' },
  { id: 'wmz', name: 'WMZ', category: 'Ultra-Creativas' },
  { id: 'wna', name: 'WNA', category: 'Ultra-Creativas' },
  { id: 'wnb', name: 'WNB', category: 'Ultra-Creativas' },
  { id: 'wnc', name: 'WNC', category: 'Ultra-Creativas' },
  { id: 'wnd', name: 'WND', category: 'Ultra-Creativas' },
  { id: 'wne', name: 'WNE', category: 'Ultra-Creativas' },
  { id: 'wnf', name: 'WNF', category: 'Ultra-Creativas' },
  { id: 'wng', name: 'WNG', category: 'Ultra-Creativas' },
  { id: 'wnh', name: 'WNH', category: 'Ultra-Creativas' },
  { id: 'wni', name: 'WNI', category: 'Ultra-Creativas' },
  { id: 'wnj', name: 'WNJ', category: 'Ultra-Creativas' },
  { id: 'wnk', name: 'WNK', category: 'Ultra-Creativas' },
  { id: 'wnl', name: 'WNL', category: 'Ultra-Creativas' },
  { id: 'wnm', name: 'WNM', category: 'Ultra-Creativas' },
  { id: 'wnn', name: 'WNN', category: 'Ultra-Creativas' },
  { id: 'wno', name: 'WNO', category: 'Ultra-Creativas' },
  { id: 'wnp', name: 'WNP', category: 'Ultra-Creativas' },
  { id: 'wnq', name: 'WNQ', category: 'Ultra-Creativas' },
  { id: 'wnr', name: 'WNR', category: 'Ultra-Creativas' },
  { id: 'wns', name: 'WNS', category: 'Ultra-Creativas' },
  { id: 'wnt', name: 'WNT', category: 'Ultra-Creativas' },
  { id: 'wnu', name: 'WNU', category: 'Ultra-Creativas' },
  { id: 'wnv', name: 'WNV', category: 'Ultra-Creativas' },
  { id: 'wnw', name: 'WNW', category: 'Ultra-Creativas' },
  { id: 'wnx', name: 'WNX', category: 'Ultra-Creativas' },
  { id: 'wny', name: 'WNY', category: 'Ultra-Creativas' },
  { id: 'wnz', name: 'WNZ', category: 'Ultra-Creativas' },
  { id: 'woa', name: 'WOA', category: 'Ultra-Creativas' },
  { id: 'wob', name: 'WOB', category: 'Ultra-Creativas' },
  { id: 'woc', name: 'WOC', category: 'Ultra-Creativas' },
  { id: 'wod', name: 'WOD', category: 'Ultra-Creativas' },
  { id: 'woe', name: 'WOE', category: 'Ultra-Creativas' },
  { id: 'wof', name: 'WOF', category: 'Ultra-Creativas' },
  { id: 'wog', name: 'WOG', category: 'Ultra-Creativas' },
  { id: 'woh', name: 'WOH', category: 'Ultra-Creativas' },
  { id: 'woi', name: 'WOI', category: 'Ultra-Creativas' },
  { id: 'woj', name: 'WOJ', category: 'Ultra-Creativas' },
  { id: 'wok', name: 'WOK', category: 'Ultra-Creativas' },
  { id: 'wol', name: 'WOL', category: 'Ultra-Creativas' },
  { id: 'wom', name: 'WOM', category: 'Ultra-Creativas' },
  { id: 'won', name: 'WON', category: 'Ultra-Creativas' },
  { id: 'woo', name: 'WOO', category: 'Ultra-Creativas' },
  { id: 'wop', name: 'WOP', category: 'Ultra-Creativas' },
  { id: 'woq', name: 'WOQ', category: 'Ultra-Creativas' },
  { id: 'wor', name: 'WOR', category: 'Ultra-Creativas' },
  { id: 'wos', name: 'WOS', category: 'Ultra-Creativas' },
  { id: 'wot', name: 'WOT', category: 'Ultra-Creativas' },
  { id: 'wou', name: 'WOU', category: 'Ultra-Creativas' },
  { id: 'wov', name: 'WOV', category: 'Ultra-Creativas' },
  { id: 'wow', name: 'WOW', category: 'Ultra-Creativas' },
  { id: 'wox', name: 'WOX', category: 'Ultra-Creativas' },
  { id: 'woy', name: 'WOY', category: 'Ultra-Creativas' },
  { id: 'woz', name: 'WOZ', category: 'Ultra-Creativas' },
  { id: 'wpa', name: 'WPA', category: 'Ultra-Creativas' },
  { id: 'wpb', name: 'WPB', category: 'Ultra-Creativas' },
  { id: 'wpc', name: 'WPC', category: 'Ultra-Creativas' },
  { id: 'wpd', name: 'WPD', category: 'Ultra-Creativas' },
  { id: 'wpe', name: 'WPE', category: 'Ultra-Creativas' },
  { id: 'wpf', name: 'WPF', category: 'Ultra-Creativas' },
  { id: 'wpg', name: 'WPG', category: 'Ultra-Creativas' },
  { id: 'wph', name: 'WPH', category: 'Ultra-Creativas' },
  { id: 'wpi', name: 'WPI', category: 'Ultra-Creativas' },
  { id: 'wpj', name: 'WPJ', category: 'Ultra-Creativas' },
  { id: 'wpk', name: 'WPK', category: 'Ultra-Creativas' },
  { id: 'wpl', name: 'WPL', category: 'Ultra-Creativas' },
  { id: 'wpm', name: 'WPM', category: 'Ultra-Creativas' },
  { id: 'wpn', name: 'WPN', category: 'Ultra-Creativas' },
  { id: 'wpo', name: 'WPO', category: 'Ultra-Creativas' },
  { id: 'wpp', name: 'WPP', category: 'Ultra-Creativas' },
  { id: 'wpq', name: 'WPQ', category: 'Ultra-Creativas' },
  { id: 'wpr', name: 'WPR', category: 'Ultra-Creativas' },
  { id: 'wps', name: 'WPS', category: 'Ultra-Creativas' },
  { id: 'wpt', name: 'WPT', category: 'Ultra-Creativas' },
  { id: 'wpu', name: 'WPU', category: 'Ultra-Creativas' },
  { id: 'wpv', name: 'WPV', category: 'Ultra-Creativas' },
  { id: 'wpw', name: 'WPW', category: 'Ultra-Creativas' },
  { id: 'wpx', name: 'WPX', category: 'Ultra-Creativas' },
  { id: 'wpy', name: 'WPY', category: 'Ultra-Creativas' },
  { id: 'wpz', name: 'WPZ', category: 'Ultra-Creativas' },
  { id: 'wqa', name: 'WQA', category: 'Ultra-Creativas' },
  { id: 'wqb', name: 'WQB', category: 'Ultra-Creativas' },
  { id: 'wqc', name: 'WQC', category: 'Ultra-Creativas' },
  { id: 'wqd', name: 'WQD', category: 'Ultra-Creativas' },
  { id: 'wqe', name: 'WQE', category: 'Ultra-Creativas' },
  { id: 'wqf', name: 'WQF', category: 'Ultra-Creativas' },
  { id: 'wqg', name: 'WQG', category: 'Ultra-Creativas' },
  { id: 'wqh', name: 'WQH', category: 'Ultra-Creativas' },
  { id: 'wqi', name: 'WQI', category: 'Ultra-Creativas' },
  { id: 'wqj', name: 'WQJ', category: 'Ultra-Creativas' },
  { id: 'wqk', name: 'WQK', category: 'Ultra-Creativas' },
  { id: 'wql', name: 'WQL', category: 'Ultra-Creativas' },
  { id: 'wqm', name: 'WQM', category: 'Ultra-Creativas' },
  { id: 'wqn', name: 'WQN', category: 'Ultra-Creativas' },
  { id: 'wqo', name: 'WQO', category: 'Ultra-Creativas' },
  { id: 'wqp', name: 'WQP', category: 'Ultra-Creativas' },
  { id: 'wqq', name: 'WQQ', category: 'Ultra-Creativas' },
  { id: 'wqr', name: 'WQR', category: 'Ultra-Creativas' },
  { id: 'wqs', name: 'WQS', category: 'Ultra-Creativas' },
  { id: 'wqt', name: 'WQT', category: 'Ultra-Creativas' },
  { id: 'wqu', name: 'WQU', category: 'Ultra-Creativas' },
  { id: 'wqv', name: 'WQV', category: 'Ultra-Creativas' },
  { id: 'wqw', name: 'WQW', category: 'Ultra-Creativas' },
  { id: 'wqx', name: 'WQX', category: 'Ultra-Creativas' },
  { id: 'wqy', name: 'WQY', category: 'Ultra-Creativas' },
  { id: 'wqz', name: 'WQZ', category: 'Ultra-Creativas' },
  { id: 'wra', name: 'WRA', category: 'Ultra-Creativas' },
  { id: 'wrb', name: 'WRB', category: 'Ultra-Creativas' },
  { id: 'wrc', name: 'WRC', category: 'Ultra-Creativas' },
  { id: 'wrd', name: 'WRD', category: 'Ultra-Creativas' },
  { id: 'wre', name: 'WRE', category: 'Ultra-Creativas' },
  { id: 'wrf', name: 'WRF', category: 'Ultra-Creativas' },
  { id: 'wrg', name: 'WRG', category: 'Ultra-Creativas' },
  { id: 'wrh', name: 'WRH', category: 'Ultra-Creativas' },
  { id: 'wri', name: 'WRI', category: 'Ultra-Creativas' },
  { id: 'wrj', name: 'WRJ', category: 'Ultra-Creativas' },
  { id: 'wrk', name: 'WRK', category: 'Ultra-Creativas' },
  { id: 'wrl', name: 'WRL', category: 'Ultra-Creativas' },
  { id: 'wrm', name: 'WRM', category: 'Ultra-Creativas' },
  { id: 'wrn', name: 'WRN', category: 'Ultra-Creativas' },
  { id: 'wro', name: 'WRO', category: 'Ultra-Creativas' },
  { id: 'wrp', name: 'WRP', category: 'Ultra-Creativas' },
  { id: 'wrq', name: 'WRQ', category: 'Ultra-Creativas' },
  { id: 'wrr', name: 'WRR', category: 'Ultra-Creativas' },
  { id: 'wrs', name: 'WRS', category: 'Ultra-Creativas' },
  { id: 'wrt', name: 'WRT', category: 'Ultra-Creativas' },
  { id: 'wru', name: 'WRU', category: 'Ultra-Creativas' },
  { id: 'wrv', name: 'WRV', category: 'Ultra-Creativas' },
  { id: 'wrw', name: 'WRW', category: 'Ultra-Creativas' },
  { id: 'wrx', name: 'WRX', category: 'Ultra-Creativas' },
  { id: 'wry', name: 'WRY', category: 'Ultra-Creativas' },
  { id: 'wrz', name: 'WRZ', category: 'Ultra-Creativas' },
  { id: 'wsa', name: 'WSA', category: 'Ultra-Creativas' },
  { id: 'wsb', name: 'WSB', category: 'Ultra-Creativas' },
  { id: 'wsc', name: 'WSC', category: 'Ultra-Creativas' },
  { id: 'wsd', name: 'WSD', category: 'Ultra-Creativas' },
  { id: 'wse', name: 'WSE', category: 'Ultra-Creativas' },
  { id: 'wsf', name: 'WSF', category: 'Ultra-Creativas' },
  { id: 'wsg', name: 'WSG', category: 'Ultra-Creativas' },
  { id: 'wsh', name: 'WSH', category: 'Ultra-Creativas' },
  { id: 'wsi', name: 'WSI', category: 'Ultra-Creativas' },
  { id: 'wsj', name: 'WSJ', category: 'Ultra-Creativas' },
  { id: 'wsk', name: 'WSK', category: 'Ultra-Creativas' },
  { id: 'wsl', name: 'WSL', category: 'Ultra-Creativas' },
  { id: 'wsm', name: 'WSM', category: 'Ultra-Creativas' },
  { id: 'wsn', name: 'WSN', category: 'Ultra-Creativas' },
  { id: 'wso', name: 'WSO', category: 'Ultra-Creativas' },
  { id: 'wsp', name: 'WSP', category: 'Ultra-Creativas' },
  { id: 'wsq', name: 'WSQ', category: 'Ultra-Creativas' },
  { id: 'wsr', name: 'WSR', category: 'Ultra-Creativas' },
  { id: 'wss', name: 'WSS', category: 'Ultra-Creativas' },
  { id: 'wst', name: 'WST', category: 'Ultra-Creativas' },
  { id: 'wsu', name: 'WSU', category: 'Ultra-Creativas' },
  { id: 'wsv', name: 'WSV', category: 'Ultra-Creativas' },
  { id: 'wsw', name: 'WSW', category: 'Ultra-Creativas' },
  { id: 'wsx', name: 'WSX', category: 'Ultra-Creativas' },
  { id: 'wsy', name: 'WSY', category: 'Ultra-Creativas' },
  { id: 'wsz', name: 'WSZ', category: 'Ultra-Creativas' },
  { id: 'wta', name: 'WTA', category: 'Ultra-Creativas' },
  { id: 'wtb', name: 'WTB', category: 'Ultra-Creativas' },
  { id: 'wtc', name: 'WTC', category: 'Ultra-Creativas' },
  { id: 'wtd', name: 'WTD', category: 'Ultra-Creativas' },
  { id: 'wte', name: 'WTE', category: 'Ultra-Creativas' },
  { id: 'wtf', name: 'WTF', category: 'Ultra-Creativas' },
  { id: 'wtg', name: 'WTG', category: 'Ultra-Creativas' },
  { id: 'wth', name: 'WTH', category: 'Ultra-Creativas' },
  { id: 'wti', name: 'WTI', category: 'Ultra-Creativas' },
  { id: 'wtj', name: 'WTJ', category: 'Ultra-Creativas' },
  { id: 'wtk', name: 'WTK', category: 'Ultra-Creativas' },
  { id: 'wtl', name: 'WTL', category: 'Ultra-Creativas' },
  { id: 'wtm', name: 'WTM', category: 'Ultra-Creativas' },
  { id: 'wtn', name: 'WTN', category: 'Ultra-Creativas' },
  { id: 'wto', name: 'WTO', category: 'Ultra-Creativas' },
  { id: 'wtp', name: 'WTP', category: 'Ultra-Creativas' },
  { id: 'wtq', name: 'WTQ', category: 'Ultra-Creativas' },
  { id: 'wtr', name: 'WTR', category: 'Ultra-Creativas' },
  { id: 'wts', name: 'WTS', category: 'Ultra-Creativas' },
  { id: 'wtt', name: 'WTT', category: 'Ultra-Creativas' },
  { id: 'wtu', name: 'WTU', category: 'Ultra-Creativas' },
  { id: 'wtv', name: 'WTV', category: 'Ultra-Creativas' },
  { id: 'wtw', name: 'WTW', category: 'Ultra-Creativas' },
  { id: 'wtx', name: 'WTX', category: 'Ultra-Creativas' },
  { id: 'wty', name: 'WTY', category: 'Ultra-Creativas' },
  { id: 'wtz', name: 'WTZ', category: 'Ultra-Creativas' },
  { id: 'wua', name: 'WUA', category: 'Ultra-Creativas' },
  { id: 'wub', name: 'WUB', category: 'Ultra-Creativas' },
  { id: 'wuc', name: 'WUC', category: 'Ultra-Creativas' },
  { id: 'wud', name: 'WUD', category: 'Ultra-Creativas' },
  { id: 'wue', name: 'WUE', category: 'Ultra-Creativas' },
  { id: 'wuf', name: 'WUF', category: 'Ultra-Creativas' },
  { id: 'wug', name: 'WUG', category: 'Ultra-Creativas' },
  { id: 'wuh', name: 'WUH', category: 'Ultra-Creativas' },
  { id: 'wui', name: 'WUI', category: 'Ultra-Creativas' },
  { id: 'wuj', name: 'WUJ', category: 'Ultra-Creativas' },
  { id: 'wuk', name: 'WUK', category: 'Ultra-Creativas' },
  { id: 'wul', name: 'WUL', category: 'Ultra-Creativas' },
  { id: 'wum', name: 'WUM', category: 'Ultra-Creativas' },
  { id: 'wun', name: 'WUN', category: 'Ultra-Creativas' },
  { id: 'wuo', name: 'WUO', category: 'Ultra-Creativas' },
  { id: 'wup', name: 'WUP', category: 'Ultra-Creativas' },
  { id: 'wuq', name: 'WUQ', category: 'Ultra-Creativas' },
  { id: 'wur', name: 'WUR', category: 'Ultra-Creativas' },
  { id: 'wus', name: 'WUS', category: 'Ultra-Creativas' },
  { id: 'wut', name: 'WUT', category: 'Ultra-Creativas' },
  { id: 'wuu', name: 'WUU', category: 'Ultra-Creativas' },
  { id: 'wuv', name: 'WUV', category: 'Ultra-Creativas' },
  { id: 'wuw', name: 'WUW', category: 'Ultra-Creativas' },
  { id: 'wux', name: 'WUX', category: 'Ultra-Creativas' },
  { id: 'wuy', name: 'WUY', category: 'Ultra-Creativas' },
  { id: 'wuz', name: 'WUZ', category: 'Ultra-Creativas' },
  { id: 'wva', name: 'WVA', category: 'Ultra-Creativas' },
  { id: 'wvb', name: 'WVB', category: 'Ultra-Creativas' },
  { id: 'wvc', name: 'WVC', category: 'Ultra-Creativas' },
  { id: 'wvd', name: 'WVD', category: 'Ultra-Creativas' },
  { id: 'wve', name: 'WVE', category: 'Ultra-Creativas' },
  { id: 'wvf', name: 'WVF', category: 'Ultra-Creativas' },
  { id: 'wvg', name: 'WVG', category: 'Ultra-Creativas' },
  { id: 'wvh', name: 'WVH', category: 'Ultra-Creativas' },
  { id: 'wvi', name: 'WVI', category: 'Ultra-Creativas' },
  { id: 'wvj', name: 'WVJ', category: 'Ultra-Creativas' },
  { id: 'wvk', name: 'WVK', category: 'Ultra-Creativas' },
  { id: 'wvl', name: 'WVL', category: 'Ultra-Creativas' },
  { id: 'wvm', name: 'WVM', category: 'Ultra-Creativas' },
  { id: 'wvn', name: 'WVN', category: 'Ultra-Creativas' },
  { id: 'wvo', name: 'WVO', category: 'Ultra-Creativas' },
  { id: 'wvp', name: 'WVP', category: 'Ultra-Creativas' },
  { id: 'wvq', name: 'WVQ', category: 'Ultra-Creativas' },
  { id: 'wvr', name: 'WVR', category: 'Ultra-Creativas' },
  { id: 'wvs', name: 'WVS', category: 'Ultra-Creativas' },
  { id: 'wvt', name: 'WVT', category: 'Ultra-Creativas' },
  { id: 'wvu', name: 'WVU', category: 'Ultra-Creativas' },
  { id: 'wvv', name: 'WVV', category: 'Ultra-Creativas' },
  { id: 'wvw', name: 'WVW', category: 'Ultra-Creativas' },
  { id: 'wvx', name: 'WVX', category: 'Ultra-Creativas' },
  { id: 'wvy', name: 'WVY', category: 'Ultra-Creativas' },
  { id: 'wvz', name: 'WVZ', category: 'Ultra-Creativas' },
  { id: 'wwa', name: 'WWA', category: 'Ultra-Creativas' },
  { id: 'wwb', name: 'WWB', category: 'Ultra-Creativas' },
  { id: 'wwc', name: 'WWC', category: 'Ultra-Creativas' },
  { id: 'wwd', name: 'WWD', category: 'Ultra-Creativas' },
  { id: 'wwe', name: 'WWE', category: 'Ultra-Creativas' },
  { id: 'wwf', name: 'WWF', category: 'Ultra-Creativas' },
  { id: 'wwg', name: 'WWG', category: 'Ultra-Creativas' },
  { id: 'wwh', name: 'WWH', category: 'Ultra-Creativas' },
  { id: 'wwi', name: 'WWI', category: 'Ultra-Creativas' },
  { id: 'wwj', name: 'WWJ', category: 'Ultra-Creativas' },
  { id: 'wwk', name: 'WWK', category: 'Ultra-Creativas' },
  { id: 'wwl', name: 'WWL', category: 'Ultra-Creativas' },
  { id: 'wwm', name: 'WWM', category: 'Ultra-Creativas' },
  { id: 'wwn', name: 'WWN', category: 'Ultra-Creativas' },
  { id: 'wwo', name: 'WWO', category: 'Ultra-Creativas' },
  { id: 'wwp', name: 'WWP', category: 'Ultra-Creativas' },
  { id: 'wwq', name: 'WWQ', category: 'Ultra-Creativas' },
  { id: 'wwr', name: 'WWR', category: 'Ultra-Creativas' },
  { id: 'wws', name: 'WWS', category: 'Ultra-Creativas' },
  { id: 'wwt', name: 'WWT', category: 'Ultra-Creativas' },
  { id: 'wwu', name: 'WWU', category: 'Ultra-Creativas' },
  { id: 'wwv', name: 'WWV', category: 'Ultra-Creativas' },
  { id: 'www', name: 'WWW', category: 'Ultra-Creativas' },
  { id: 'wwx', name: 'WWX', category: 'Ultra-Creativas' },
  { id: 'wwy', name: 'WWY', category: 'Ultra-Creativas' },
  { id: 'wwz', name: 'WWZ', category: 'Ultra-Creativas' },
  { id: 'wxa', name: 'WXA', category: 'Ultra-Creativas' },
  { id: 'wxb', name: 'WXB', category: 'Ultra-Creativas' },
  { id: 'wxc', name: 'WXC', category: 'Ultra-Creativas' },
  { id: 'wxd', name: 'WXD', category: 'Ultra-Creativas' },
  { id: 'wxe', name: 'WXE', category: 'Ultra-Creativas' },
  { id: 'wxf', name: 'WXF', category: 'Ultra-Creativas' },
  { id: 'wxg', name: 'WXG', category: 'Ultra-Creativas' },
  { id: 'wxh', name: 'WXH', category: 'Ultra-Creativas' },
  { id: 'wxi', name: 'WXI', category: 'Ultra-Creativas' },
  { id: 'wxj', name: 'WXJ', category: 'Ultra-Creativas' },
  { id: 'wxk', name: 'WXK', category: 'Ultra-Creativas' },
  { id: 'wxl', name: 'WXL', category: 'Ultra-Creativas' },
  { id: 'wxm', name: 'WXM', category: 'Ultra-Creativas' },
  { id: 'wxn', name: 'WXN', category: 'Ultra-Creativas' },
  { id: 'wxo', name: 'WXO', category: 'Ultra-Creativas' },
  { id: 'wxp', name: 'WXP', category: 'Ultra-Creativas' },
  { id: 'wxq', name: 'WXQ', category: 'Ultra-Creativas' },
  { id: 'wxr', name: 'WXR', category: 'Ultra-Creativas' },
  { id: 'wxs', name: 'WXS', category: 'Ultra-Creativas' },
  { id: 'wxt', name: 'WXT', category: 'Ultra-Creativas' },
  { id: 'wxu', name: 'WXU', category: 'Ultra-Creativas' },
  { id: 'wxv', name: 'WXV', category: 'Ultra-Creativas' },
  { id: 'wxw', name: 'WXW', category: 'Ultra-Creativas' },
  { id: 'wxx', name: 'WXX', category: 'Ultra-Creativas' },
  { id: 'wxy', name: 'WXY', category: 'Ultra-Creativas' },
  { id: 'wxz', name: 'WXZ', category: 'Ultra-Creativas' },
  { id: 'wya', name: 'WYA', category: 'Ultra-Creativas' },
  { id: 'wyb', name: 'WYB', category: 'Ultra-Creativas' },
  { id: 'wyc', name: 'WYC', category: 'Ultra-Creativas' },
  { id: 'wyd', name: 'WYD', category: 'Ultra-Creativas' },
  { id: 'wye', name: 'WYE', category: 'Ultra-Creativas' },
  { id: 'wyf', name: 'WYF', category: 'Ultra-Creativas' },
  { id: 'wyg', name: 'WYG', category: 'Ultra-Creativas' },
  { id: 'wyh', name: 'WYH', category: 'Ultra-Creativas' },
  { id: 'wyi', name: 'WYI', category: 'Ultra-Creativas' },
  { id: 'wyj', name: 'WYJ', category: 'Ultra-Creativas' },
  { id: 'wyk', name: 'WYK', category: 'Ultra-Creativas' },
  { id: 'wyl', name: 'WYL', category: 'Ultra-Creativas' },
  { id: 'wym', name: 'WYM', category: 'Ultra-Creativas' },
  { id: 'wyn', name: 'WYN', category: 'Ultra-Creativas' },
  { id: 'wyo', name: 'WYO', category: 'Ultra-Creativas' },
  { id: 'wyp', name: 'WYP', category: 'Ultra-Creativas' },
  { id: 'wyq', name: 'WYQ', category: 'Ultra-Creativas' },
  { id: 'wyr', name: 'WYR', category: 'Ultra-Creativas' },
  { id: 'wys', name: 'WYS', category: 'Ultra-Creativas' },
  { id: 'wyt', name: 'WYT', category: 'Ultra-Creativas' },
  { id: 'wyu', name: 'WYU', category: 'Ultra-Creativas' },
  { id: 'wyv', name: 'WYV', category: 'Ultra-Creativas' },
  { id: 'wyw', name: 'WYW', category: 'Ultra-Creativas' },
  { id: 'wyx', name: 'WYX', category: 'Ultra-Creativas' },
  { id: 'wyy', name: 'WYY', category: 'Ultra-Creativas' },
  { id: 'wyz', name: 'WYZ', category: 'Ultra-Creativas' },
  { id: 'wza', name: 'WZA', category: 'Ultra-Creativas' },
  { id: 'wzb', name: 'WZB', category: 'Ultra-Creativas' },
  { id: 'wzc', name: 'WZC', category: 'Ultra-Creativas' },
  { id: 'wzd', name: 'WZD', category: 'Ultra-Creativas' },
  { id: 'wze', name: 'WZE', category: 'Ultra-Creativas' },
  { id: 'wzf', name: 'WZF', category: 'Ultra-Creativas' },
  { id: 'wzg', name: 'WZG', category: 'Ultra-Creativas' },
  { id: 'wzh', name: 'WZH', category: 'Ultra-Creativas' },
  { id: 'wzi', name: 'WZI', category: 'Ultra-Creativas' },
  { id: 'wzj', name: 'WZJ', category: 'Ultra-Creativas' },
  { id: 'wzk', name: 'WZK', category: 'Ultra-Creativas' },
  { id: 'wzl', name: 'WZL', category: 'Ultra-Creativas' },
  { id: 'wzm', name: 'WZM', category: 'Ultra-Creativas' },
  { id: 'wzn', name: 'WZN', category: 'Ultra-Creativas' },
  { id: 'wzo', name: 'WZO', category: 'Ultra-Creativas' },
  { id: 'wzp', name: 'WZP', category: 'Ultra-Creativas' },
  { id: 'wzq', name: 'WZQ', category: 'Ultra-Creativas' },
  { id: 'wzr', name: 'WZR', category: 'Ultra-Creativas' },
  { id: 'wzs', name: 'WZS', category: 'Ultra-Creativas' },
  { id: 'wzt', name: 'WZT', category: 'Ultra-Creativas' },
  { id: 'wzu', name: 'WZU', category: 'Ultra-Creativas' },
  { id: 'wzv', name: 'WZV', category: 'Ultra-Creativas' },
  { id: 'wzw', name: 'WZW', category: 'Ultra-Creativas' },
  { id: 'wzx', name: 'WZX', category: 'Ultra-Creativas' },
  { id: 'wzy', name: 'WZY', category: 'Ultra-Creativas' },
  { id: 'wzz', name: 'WZZ', category: 'Ultra-Creativas' }
] as const;

export type VariantId = typeof ALL_VARIANTS[number]['id'];
export type VariantCategory = typeof ALL_VARIANTS[number]['category'];

// Propiedades editables por tipo de componente
export interface ComponentEditableProperties {
  // Propiedades comunes a todos
  common: string[];
  // Propiedades específicas por tipo
  button?: string[];
  card?: string[];
  input?: string[];
  section?: string[];
  hero?: string[];
  navbar?: string[];
  footer?: string[];
  modal?: string[];
  table?: string[];
  form?: string[];
  title?: string[];
  chart?: string[];
  pricing?: string[];
  newsletter?: string[];
  steps?: string[];
  breadcrumbs?: string[];
  spinner?: string[];
  accordion?: string[];
  tabs?: string[];
  list?: string[];
  chip?: string[];
  gallery?: string[];
}

export const EDITABLE_PROPERTIES: ComponentEditableProperties = {
  common: [
    'backgroundColor',
    'color',
    'padding',
    'margin',
    'borderRadius',
    'border',
    'boxShadow',
    'backdropFilter',
    'opacity',
    'width',
    'height',
    'minWidth',
    'minHeight',
    'maxWidth',
    'maxHeight',
    'zIndex',
    'position',
    'top',
    'bottom',
    'left',
    'right',
    'overflow'
  ],
  button: [
    'fontSize',
    'fontWeight',
    'textTransform',
    'letterSpacing',
    'cursor',
    'transition'
  ],
  card: [
    'overflow',
    'backgroundImage',
    'backgroundSize',
    'backgroundPosition'
  ],
  input: [
    'fontSize',
    'fontWeight',
    'lineHeight',
    'outline',
    'borderColor',
    'focusBorderColor'
  ],
  section: [
    'backgroundImage',
    'backgroundSize',
    'backgroundPosition',
    'backgroundAttachment',
    'minHeight',
    'display',
    'flexDirection',
    'justifyContent',
    'alignItems',
    'gap'
  ],
  hero: [
    'backgroundImage',
    'backgroundSize',
    'backgroundPosition',
    'minHeight',
    'textAlign',
    'display',
    'flexDirection',
    'justifyContent',
    'alignItems'
  ],
  navbar: [
    'position',
    'top',
    'left',
    'right',
    'zIndex',
    'display',
    'justifyContent',
    'alignItems',
    'gap'
  ],
  footer: [
    'display',
    'flexDirection',
    'justifyContent',
    'alignItems',
    'gap',
    'textAlign'
  ],
  modal: [
    'zIndex',
    'position',
    'top',
    'left',
    'transform',
    'maxWidth',
    'maxHeight',
    'overflow'
  ],
  table: [
    'borderCollapse',
    'borderSpacing',
    'width',
    'tableLayout'
  ],
  form: [
    'display',
    'flexDirection',
    'gap',
    'alignItems'
  ],
  title: [
    'fontSize',
    'fontWeight',
    'textAlign',
    'textTransform',
    'letterSpacing',
    'lineHeight'
  ],
  chart: [
    'height',
    'width',
    'padding',
    'margin'
  ],
  accordion: [
    'gap',
    'padding',
    'margin'
  ],
  tabs: [
    'gap',
    'padding'
  ],
  list: [
    'gap',
    'padding',
    'fontSize'
  ],
  chip: [
    'fontSize',
    'fontWeight',
    'padding'
  ],
  gallery: [
    'gap',
    'gridTemplateColumns',
    'padding'
  ],
  pricing: [
    'gap',
    'padding',
    'margin'
  ],
  newsletter: [
   'padding',
   'margin',
   'backgroundImage'
 ],
 steps: [
   'gap',
   'padding'
 ],
 breadcrumbs: [
   'fontSize',
   'color'
 ],
 spinner: [
   'width',
   'height',
   'color'
 ]
};

// Detectar tipo de componente basado en su estructura
export function detectComponentType(element: any): keyof ComponentEditableProperties {
  if (!element) return 'common';
  
  const type = element.type?.toLowerCase() || '';
  const tagName = element.tagName?.toLowerCase() || '';
  const className = element.className || '';
  
  // Detectar por tipo explícito
  if (type.includes('button') || tagName === 'button') return 'button';
  if (type.includes('card')) return 'card';
  if (type.includes('input') || tagName === 'input') return 'input';
  if (type.includes('section') || tagName === 'section') return 'section';
  if (type.includes('hero')) return 'hero';
  if (type.includes('navbar') || type.includes('nav')) return 'navbar';
  if (type.includes('footer')) return 'footer';
  if (type.includes('modal')) return 'modal';
  if (type.includes('table') || tagName === 'table') return 'table';
  if (type.includes('form') || tagName === 'form') return 'form';
  if (type.includes('title') || type.includes('subtitle') || (tagName >= 'h1' && tagName <= 'h6')) return 'title';
  if (type.includes('chart')) return 'chart';
  if (type.includes('accordion') || type.includes('faq')) return 'accordion';
  if (type.includes('tabs')) return 'tabs';
  if (type.includes('list')) return 'list';
  if (type.includes('chip')) return 'chip';
  if (type.includes('gallery')) return 'gallery';
  if (type.includes('pricing')) return 'pricing';
  if (type.includes('newsletter')) return 'newsletter';
  if (type.includes('steps')) return 'steps';
  if (type.includes('breadcrumbs')) return 'breadcrumbs';
  if (type.includes('spinner')) return 'spinner';
  
  // Detectar por clase
  if (className.includes('card')) return 'card';
  if (className.includes('btn') || className.includes('button')) return 'button';
  if (className.includes('hero')) return 'hero';
  if (className.includes('nav')) return 'navbar';
  if (className.includes('footer')) return 'footer';
  
  return 'common';
}

// Obtener propiedades editables para un componente
export function getEditableProperties(element: any): string[] {
  const componentType = detectComponentType(element);
  const specificProps = EDITABLE_PROPERTIES[componentType] || [];
  return [...EDITABLE_PROPERTIES.common, ...specificProps];
}
